# Modified version of https://dev.to/achukka/deploy-react-app-using-github-actions-157d
name: Deploy React Application

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
    
      - name: npm ci, postintstall, build, and test
        run: |
          npm ci
          npm postinstall --if-present
          npm run build --if-present
          npm test --if-present

      - name: deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./build          
